<?php

use Fisharebest\Webtrees\I18N;

?>

<div style="margin-left:8%; width:60%">
    
<h2><?= $title ?></h2>

<h3><?= I18N::translate('Personal data') ?></h3>

<ul>
    <li>
        <p><?= I18N::translate('This website processes personal data for the purpose of historical and genealogical research.') ?></p>
    </li>
    <li>
        <p><?= I18N::translate('This research is a “legitimate interest” under article 6(f) of the EU General Data Protection Regulations.') ?></p>
    </li>
    <li>
        <p><span style="color:red">All of us acknowledge the paramount importance of personal data protection on this family tree site and we work hard to protect our data.</span> Fortunately, webtrees has excellent privacy features and allows you to enforce certain privacy policies - our site hides live information from those visitors who are not registered. In order to view information about living persons, you must be a trusted member of our site and you must log in to it with your username and password. Your membership will allow you to access your personal family tree page.</p>
    </li>
    <li>
        <p>In addition, our site works with several levels of user access to both personal information and the display of relationships between individuals and families. The second tool gives you access to data on people identified as close relatives. If you join as a registered member and some people or families appear to you as 'private', this is due to your user account settings. If you think your access is too limited, you can contact the family tree administrator to explain where you are blocked and why you think you shouldn't be.</p>
    </li>
    <li>
        <p>No system is perfect, and there is always the possibility that someone will break into it and gain unwanted access to data. If you have serious concerns about your personal information on this site, please let us know by email to the family tree administrator. Your data will be removed from your family tree, but your access may be restricted at the same time. <span style="color:red">We take the misuse of our data seriously and will not tolerate theft or misuse of it. We will take legal action against those who engage in or cause attempted identity theft or harassment using the information obtained here.</span></p>
    </li>
    <li>
        <p>Do not copy our living information to any other sites or places where you are unable to guarantee the privacy of those individuals. You may be responsible for its detection or misuse. As you will know, a lot of time, effort and talent has been put into this database. We do not want others to simply copy our work together. We also do not share the information contained herein with other sources, nor do we contribute our data to commercial projects (Ancestry.com, Geni, Tribal Pages, MyHeritage, etc.). We expect you to follow these guidelines as well. Please do not copy our data to other sites and in no case publish data about living persons elsewhere. This database will remain our property for the public display of publicly available data and will not be sold, donated or rented in any way for profit, whether ours or someone else's. We will not share personal information with any public source and we commit you as our user to the same.</p>
    </li>
    <li>
        <p>Keep in mind that your password is important for the protection of your personal and other families' data, so keep it safe. We recommend that you change your password from time to time. Please note that the family manager does not have access to your password. If you forget them, use the 'Request a new password' request on the pedigree homepage. You will receive a new temporary password at your registered e-mail address.</p>
    </li>
</ul>

<h3><?= I18N::translate('Cookies') ?></h3>

<ul>
    <li>
        <p><?= I18N::translate('This website uses cookies to enable login sessions, and to remember preferences such as your chosen language.') ?></p>
    </li>
    <li>
        <p><?= I18N::translate('These cookies are “essential”, and do not require consent.') ?></p>
    </li>
    <li>
        <p>Some websites use so-called cookies. Cookies do not harm your computer and do not contain viruses. Cookies are used to make our offer more user-friendly, efficient and secure. Cookies are small text files that your browser stores on your computer.</p>
    </li>
    <li>
        <p>Most of the cookies we use are so-called "relational cookies". They are automatically deleted after your visit. Other cookies remain on your device until you delete them. These cookies allow us to recognize your browser on your next visit.</p>
    </li>
    <li>
        <p>You can set your browser to be informed about cookie settings, allow cookies only in individual cases, exclude the acceptance of cookies in certain cases or in general, and enable automatic deletion of cookies when the browser is closed. If you disable cookies, the functionality of this website may be limited.</p>
    </li>
</ul>

<?php if ($analytics->isNotEmpty()) : ?>
    <h3><?= I18N::translate('Tracking and analytics') ?></h3>

    <ul>
        <li>
            <?= I18N::translate('This website uses third-party services to learn about visitor behavior.') ?>
            <ul>
                <?php foreach ($analytics as $module) : ?>
                    <li>
                        <?= $module->title() ?> —
                        <a href="<?= e($module->externalUrl()) ?>"><?= e($module->externalUrl()) ?></a>
                    </li>
                <?php endforeach ?>
            </ul>
        </li>

        <li>
            <?= I18N::translate('These services may use cookies or other tracking technology.') ?>
        </li>

        <li>
            <?= I18N::translate('You can opt out of tracking by setting the “Do Not Track” header in your browser preferences.') ?>
        </li>
    </ul>
<?php endif ?>

<h3><?= I18N::translate('Data controller') ?></h3>

<ul>
    <li>
        <?= I18N::translate('This website is operated by the following individuals.') ?>

        <ul>
            <?php foreach ($administrators as $administrator) : ?>
                <li>
                    <?php echo($contactlinks[$administrator->id()]) ?>

                </li>
            <?php endforeach ?>
        </ul>

    </li>
</ul>

</div>