<?php

use Fisharebest\Webtrees\I18N;

?>
<div style="margin-left:8%; width:60%">

<h2><?= $title ?></h2>

<h3><?= I18N::translate('Personal data') ?></h3>

<ul>
    <li>
        <p><?= I18N::translate('This website processes personal data for the purpose of historical and genealogical research.') ?></p>
    </li>
    <li>
        <p><?= I18N::translate('This research is a “legitimate interest” under article 6(f) of the EU General Data Protection Regulations.') ?></p>
    </li>
    <li>
    <p><span style="color:red">Všichni z nás na těchto stránkách rodokmenu uznáváme prvořadou důležitost ochrany osobních údajů a usilovně naše údaje chráníme.</span> Naštěstí produkt webtrees má výtečné prostředky k ochraně osobních údajů a umožňuje uplatňovat určitá pravidla soukromí - naše stránky ukrývají údaje o žijících osobách před těmi návštěvníky, kteří nejsou registrováni. Abyste mohli prohlížet údaje o žijících osobách, musíte být důvěryhodným členem našich stránek a musíte se k nim přihlásit svým uživatelským jménem a heslem. Vaše členství vám dovolí přístup k vaší osobní stránce v rodokmenu.</p>
    </li>
    <li>
    <p>Navíc naše stránky pracují s několika úrovněmi přístupového oprávnění uživatelů jak k údajům o osobách, tak k zobrazování vztahů mezi osobami a rodinami. Ten druhý nástroj vám umožní přístup k údajům o osobách označených jako blízcí příbuzní. Jestliže se připojíte jako registrovaný člen a některé osoby nebo rodiny se vám zobrazí jako 'soukromé', je to způsobeno nastavením vašeho uživatelského účtu. Pokud je podle vašeho názoru váš přístup příliš omezený, můžete se obrátit na správce rodokmenu a vysvětlit, kde jste blokováni a proč si myslíte, že byste být neměli.</p>
    </li>
    <li>
    <p>Žádný systém není dokonalý a vždy existuje nějaká možnost, že se do něj někdo vlomí a získá nežádoucí přístup k údajům. Pokud máte vážné obavy o svoje osobní údaje na těchto stránkách, sdělte to e-mailem správci rodokmenu. Vaše údaje budou z rodokmenu odstraněny, ale současně může být omezen i váš přístup. <span style="color:red">Zneužití našich údajů bereme vážně a nebudeme tolerovat jejich krádež nebo zneužití. Proti těm, kteří se zúčastní pokusu o krádež totožnosti či obtěžování pomocí zde získaných údajů nebo je způsobí, podnikneme právní kroky.</span></p>
    </li>
    <li>
<p>Nekopírujte naše údaje o žijících osobách na žádné jiné stránky nebo místa, kde nejste schopni zaručit soukromí těchto osob. Mohli byste nést zodpovědnost za jeho odhalení nebo zneužití. Jak je vám jistě zřejmé, k pořízení této databáze bylo vynaloženo mnoho času, úsilí a talentu. Nechceme, aby jiní jednoduše kopírovali naše společné dílo. Nesdílíme také zde obsažené informace s jinými prameny, ani nepřispíváme svými údaji do komerčních projektů (Ancestry.com, Geni, Tribal Pages, MyHeritage, atd.). Očekáváme, že budete tyto zásady dodržovat také. Prosíme, nekopírujte naše údaje na jiné stránky a v žádném případě nezveřejňujte údaje o žijících osobách někde jinde. Tato databáze zůstane naším vlastnictvím pro veřejné zobrazení veřejně přípustných údajů a nebude žádným způsobem prodána, darována ani pronajata za účelem zisku, ať našeho nebo cizího. Osobní údaje nebudeme sdílet s žádným veřejným pramenem a vás jako naše uživatele zavazujeme k témuž.</p>
    </li>
    <li>
<p>Mějte na paměti, že vaše heslo je podstatné pro ochranu vašich osobních údajů a údajů ostatních rodin, proto je bezpečně uložte. Doporučujeme heslo čas od času měnit. Vězte, že správce rodomenu nemá k vašemu heslu přístup. Jestliže je zapomenete, použijte požadavek 'Zažádat o nové heslo' na domovské stránce rodokmenu. Nové dočasné heslo dostanete na vaši registrovanou e-mailovou adresu.</p>
    </li>
</ul>


<h3><?= I18N::translate('Cookies') ?></h3>

<ul>
    <li>
        <p><?= I18N::translate('This website uses cookies to enable login sessions, and to remember preferences such as your chosen language.') ?></p>
    </li>
    <li>
        <p><?= I18N::translate('These cookies are “essential”, and do not require consent.') ?></p>
    </li>
    <li>
<p>Některé webové stránky používají takzvané cookies. Soubory cookie nepoškozují váš počítač a neobsahují viry. Cookies slouží k tomu, aby byla naše nabídka uživatelsky přívětivější, efektivnější a bezpečnější. Cookies jsou malé textové soubory, které ukládá váš prohlížeč do vašeho počítače.</p>
    </li>
    <li>
<p>Většina souborů cookie, které používáme, jsou takzvané „relační soubory cookie“. Po vaší návštěvě jsou automaticky smazány. Ostatní soubory cookie zůstanou uloženy ve vašem zařízení, dokud je nevymažete. Tyto soubory cookie nám umožňují rozpoznat váš prohlížeč při příští návštěvě.</p>
    </li>
    <li>
<p>Svůj prohlížeč můžete nastavit tak, abyste byli informováni o nastavení souborů cookie, a povolit soubory cookie pouze v jednotlivých případech, vyloučit přijímání souborů cookie v určitých případech nebo obecně a aktivovat automatické mazání souborů cookie při zavření prohlížeče. Pokud deaktivujete cookies, může být funkčnost tohoto webu omezena.</p>
    </li>
</ul>


<?php if ($analytics->isNotEmpty()) : ?>
    <h3><?= I18N::translate('Tracking and analytics') ?></h3>

    <ul>
        <li>
            <?= I18N::translate('This website uses third-party services to learn about visitor behavior.') ?>
            <ul>
                <?php foreach ($analytics as $module) : ?>
                    <li>
                        <?= $module->title() ?> —
                        <a href="<?= e($module->externalUrl()) ?>"><?= e($module->externalUrl()) ?></a>
                    </li>
                <?php endforeach ?>
            </ul>
        </li>

        <li>
            <?= I18N::translate('These services may use cookies or other tracking technology.') ?>
        </li>

        <li>
            <?= I18N::translate('You can opt out of tracking by setting the “Do Not Track” header in your browser preferences.') ?>
        </li>
    </ul>
<?php endif ?>

<h3><?= I18N::translate('Data controller') ?></h3>

<ul>
    <li>
        <?= I18N::translate('This website is operated by the following individuals.') ?>

        <ul>
            <?php foreach ($administrators as $administrator) : ?>
                <li>
                    <?php echo($contactlinks[$administrator->id()]) ?>


                </li>
            <?php endforeach ?>
        </ul>

    </li>
</ul>

</div>

