<?php

use Fisharebest\Webtrees\I18N;

?>

<div style="margin-left:8%; width:60%">
    
<h2><?= $title ?></h2>

<h3><?= I18N::translate('Personal data') ?></h3>

<ul>
    <li>
        <?= I18N::translate('This website processes personal data for the purpose of historical and genealogical research.') ?>
    </li>
    <li>
        <?= I18N::translate('This research is a “legitimate interest” under article 6(f) of the EU General Data Protection Regulations.') ?>
    </li>
</ul>

<h3><?= I18N::translate('Cookies') ?></h3>

<ul>
    <li>
        <?= I18N::translate('This website uses cookies to enable login sessions, and to remember preferences such as your chosen language.') ?>
    </li>
    <li>
        <?= I18N::translate('These cookies are “essential”, and do not require consent.') ?>
    </li>
</ul>

</div>